// This file is automatically generated. Do not edit it directly.
// Powered by EnterCloud Managed Supabase
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spb-t4n096zlnw1gm30w.supabase.opentrust.net";
const SUPABASE_PUBLISHABLE_KEY = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiYW5vbiIsInJlZiI6InNwYi10NG4wOTZ6bG53MWdtMzB3IiwiaXNzIjoic3VwYWJhc2UiLCJpYXQiOjE3ODM5NDkzNTksImV4cCI6MjA5OTUyNTM1OX0.fGo6iMbFtsmxWXfQgLAY1iGcrr3mC4DbNOcSsrAOB2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
